/* This function returns a React component that represents the header of the page.
The `generatedPassword` prop is the password that was generated by the user.
The `copyToClipboard` prop is a function that copies the password to the clipboard.  */
export default function Header({ generatedPassword, copyToClipboard }) {
  return (
    <header>
      <div id="head-gendiv">
        {generatedPassword ? generatedPassword : "P4$5W0rD!P4$5W0rD!34"}
      </div>
      <div id="head-icondiv" onClick={copyToClipboard}>
        <img src="./images/copy.png" id="icon-copy" alt="" />
      </div>
    </header>
  );
}
